// src/pages/Login.tsx
import React, { useState } from 'react';
import { useStore } from '@/context/store';
import { RouteComponentProps } from 'react-router-dom';
import { toast } from 'react-toastify';
import './Login.css';
import 'react-toastify/dist/ReactToastify.css';

interface Props extends RouteComponentProps {}

export const Login: React.FC<Props> = (props) => {
  const loginForm = useForm();
  const { authStore } = useStore();
  const { history } = props;

  const handleLoginFormSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const { username, password } = loginForm.form;
    if (username === '') {
      toast('username is required', {
        autoClose: 1000,
      });
      return;
    }

    if (password === '') {
      toast('password is required', {
        autoClose: 1000,
      });
      return;
    }

    const res = await authStore.login({ username, password });
    if (res.error) {
      toast(res.error.message, {
        autoClose: 1000,
      });
      return;
    }

    toast('hi!', {
      autoClose: 1000,
    });

    history.push('/');
  };

  return (
    <div className="login-page">
      <div className="login-form">
        <h2 className="app-title-h2">APAS TODO</h2>
        <form onSubmit={handleLoginFormSubmit}>
          <div className="form-group">
            <input
              name="username"
              placeholder="Username"
              onChange={loginForm.handleChanged}
              className="input-login-form form-control"
            />
          </div>
          <div className="form-group">
            <input
              name="password"
              type="password"
              placeholder="Password"
              onChange={loginForm.handleChanged}
              className="input-login-form form-control"
            />
          </div>

          <button type="submit" className="btn-login-form btn btn-primary">
            Login
          </button>
        </form>
      </div>
    </div>
  );
};

const useForm = () => {
  const [form, setForm] = useState({
    username: '',
    password: '',
  });

  return {
    form,
    handleChanged: (e: React.ChangeEvent<HTMLInputElement>) => {
      const { name, value } = e.target;

      setForm({
        ...form,
        [name]: value,
      });
    },
  };
};

// src/views/Login.vue
<template>
  <div class="auth-page">
    <div class="container page">
      <div class="row">
        <div class="col-md-6 offset-md-3 col-xs-12">
          <h1 class="text-xs-center title">Sign in</h1>
          <p class="text-xs-center">
            <router-link :to="{ name: 'register' }">Need an account?</router-link>
          </p>
          <ul v-if="errors" class="error-messages">
            <li v-for="(v, k) in errors" :key="k">{{ k }} {{ v }}</li>
          </ul>
          <form v-on:submit.prevent="onSubmit(username, password);">
            <fieldset class="form-group">
              <input
                class="input form-control form-control-lg"
                type="text"
                v-model="username"
                placeholder="Username"
              />
            </fieldset>
            <fieldset class="form-group">
              <input
                class="input form-control form-control-lg"
                type="password"
                v-model="password"
                placeholder="Password"
              />
            </fieldset>
            <button class="button btn btn-lg btn-primary pull-xs-right">Sign in</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
import { mapState } from 'vuex';
import { LOGIN } from '@/store/actions.type';

export default {
  data() {
    return {
      username: '',
      password: '',
    };
  },

  methods: {
    onSubmit(username, password) {
      this.$store
        .dispatch(LOGIN, { username, password })
        .then(() => this.$router.push({ name: 'home' }));
    },
  },
  computed: {
    ...mapState({
      errors: state => state.auth.errors,
    }),
  },
};
</script>
